/*
 * Copyright 2014 Pompeu.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.solutions.pompeu.view;

import com.solutions.pompeu.control.CartaoConsumacaoControl;
import com.solutions.pompeu.model.CartaoConsumacaoDAO;
import com.solutions.pompeu.model.ProdutoDAO;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pompeu
 */
public class VendasCartaoConsumacao extends JFrame {

    protected double valorun;
    protected double valortotal;
    protected double total;
    protected double saldo;
    protected int quant, fechar = 0;
    protected long venda_id;
    protected Principal principal;

    //formantando os valores de saida
    protected NumberFormat nf = new DecimalFormat("R$ #,##0.00", new DecimalFormatSymbols(new Locale("pt", "BR")));

    public VendasCartaoConsumacao() {
        initComponents();
        ajustarColunas();
        this.setLocation(300, 80);
        hablitarDesabilitacapus(true);
        this.venda_id = new CartaoConsumacaoDAO().inserirIdVenda();
    }

    public VendasCartaoConsumacao(Principal principal) {
        this();
        this.principal = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNumeroCartao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfProduto = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        jlNomePropretario = new javax.swing.JLabel();
        jlNomeProduto = new javax.swing.JLabel();
        btnAtulizar = new javax.swing.JButton();
        btnDelatar = new javax.swing.JButton();
        tfQunatidade = new javax.swing.JTextField();
        jlSaldo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jlMensagem = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlSaldoFuturo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlTotalCompra = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnFecharVenda = new javax.swing.JButton();
        btnCancelarVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Vendas");
        setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jPanel1.setForeground(java.awt.Color.red);

        jLabel1.setText("Numero Cartao");

        tfNumeroCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroCartaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Proprietario");

        jLabel3.setText("Codigo Produto");

        jLabel4.setText("Quantidade");

        tfProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProdutoActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        jlNomePropretario.setForeground(java.awt.Color.red);
        jlNomePropretario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jlNomeProduto.setForeground(java.awt.Color.red);

        btnAtulizar.setText("Atualizar");
        btnAtulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtulizarActionPerformed(evt);
            }
        });

        btnDelatar.setText("Delatar");
        btnDelatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelatarActionPerformed(evt);
            }
        });

        jlSaldo.setForeground(java.awt.Color.red);

        jLabel7.setText("Saldo Atual do Cartao");

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        tblVenda.setAutoCreateRowSorter(true);
        tblVenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Quantidade", "Valor UN", " Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVenda.getTableHeader().setReorderingAllowed(false);
        tblVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblVendaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblVenda);
        if (tblVenda.getColumnModel().getColumnCount() > 0) {
            tblVenda.getColumnModel().getColumn(0).setResizable(false);
            tblVenda.getColumnModel().getColumn(1).setResizable(false);
            tblVenda.getColumnModel().getColumn(2).setResizable(false);
            tblVenda.getColumnModel().getColumn(3).setResizable(false);
            tblVenda.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );

        jlMensagem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlMensagem.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMensagem)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jlMensagem)
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel6.setText("Saldo Futuro do  Cartao");

        jlSaldoFuturo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlSaldoFuturo.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlSaldoFuturo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlSaldoFuturo)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel5.setText("Total da Compra");

        jlTotalCompra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlTotalCompra.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTotalCompra)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel6, jPanel7});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel6, jPanel7});

        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnFecharVenda.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnFecharVenda.setText("Confirmar Venda");
        btnFecharVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharVendaActionPerformed(evt);
            }
        });

        btnCancelarVenda.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnCancelarVenda.setText("Cancelar Venda");
        btnCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFecharVenda)
                .addContainerGap())
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarVenda, btnFecharVenda});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(btnFecharVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfQunatidade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNumeroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jlNomePropretario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtulizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelatar)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jlNomeProduto))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlSaldo)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAtulizar, btnDelatar, btnInserir});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfProduto, tfQunatidade});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfNumeroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNomePropretario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSaldo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNomeProduto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(tfQunatidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnInserir)
                                .addComponent(btnAtulizar)
                                .addComponent(btnDelatar))))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfNumeroCartao, tfProduto, tfQunatidade});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAtulizar, btnDelatar, btnInserir});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel3, jPanel9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNumeroCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroCartaoActionPerformed
        // TODO add your handling code here:
        long numeroCartao = 0;
        try {
            numeroCartao = Long.parseLong(tfNumeroCartao.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        CartaoConsumacaoDAO CartaoDao = new CartaoConsumacaoDAO();
        String nome;
        nome = CartaoDao.listaCartao(numeroCartao).getNome();
        if (nome != null) {
            jlNomePropretario.setText(nome);
            CartaoConsumacaoDAO CartaoDao2 = new CartaoConsumacaoDAO();
            saldo = CartaoDao2.cartaoSAldo(numeroCartao);
            String saldoAtual = String.valueOf(nf.format(saldo));
            jlSaldo.setText(saldoAtual);
            jlMensagem.setText(null);

        } else {
            jlMensagem.setText("Numero invalido do cartao");
        }
        hablitarDesabilitacapus(false);

    }//GEN-LAST:event_tfNumeroCartaoActionPerformed

    private void tfProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProdutoActionPerformed
        // TODO add your handling code here:
        tfQunatidade.setText(null);
        long numero = 0;
        try {
            numero = Long.parseLong(tfProduto.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        ProdutoDAO prodDao = new ProdutoDAO();
        String nomeProduto;
        nomeProduto = prodDao.buscarProdutoId(numero).getNome();
        ProdutoDAO prodDao2 = new ProdutoDAO();
        valorun = prodDao2.buscarProdutoId(numero).getPreco();
        jlNomeProduto.setText(nomeProduto);

    }//GEN-LAST:event_tfProdutoActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        jlMensagem.setText(null);
        tfNumeroCartao.setEditable(false);

        DefaultTableModel modelo = (DefaultTableModel) tblVenda.getModel();

        String quantidade = tfQunatidade.getText();
        try {
            quant = Integer.parseInt(quantidade);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        valortotal = valorun * quant;

        if (!tfNumeroCartao.getText().trim().equals("") && !tfProduto.getText().trim().equals("")
                && quant > 0) {
            modelo.addRow(new Object[]{tfProduto.getText(), jlNomeProduto.getText(),
                quant, valorun, valortotal});
            CartaoConsumacaoControl cartaoControl = new CartaoConsumacaoControl();
            long prod_id = Long.parseLong(tfProduto.getText());

            int quantVenda = quant;

            cartaoControl.produtoMovimentacaoinserir(prod_id, venda_id, quantVenda);

        } else {
            JOptionPane.showMessageDialog(this, "Algum(s) campo(s) invalido(s)");
        }
        calctotal();

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAtulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtulizarActionPerformed
        // TODO add your handling code here:
        jlMensagem.setText("");

        DefaultTableModel modelo = (DefaultTableModel) tblVenda.getModel();
        String quantidade = tfQunatidade.getText();
        try {
            quant = Integer.parseInt(quantidade);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        valortotal = valorun * quant;

        if (tblVenda.getSelectedRow() == -1) {
            if (tblVenda.getRowCount() == 0) {
                jlMensagem.setText("Tabela sem produtos");
            } else {
                jlMensagem.setText("Selecione um produto");
            }
        } else {
            modelo.setValueAt(tfProduto.getText(), tblVenda.getSelectedRow(), 0);
            modelo.setValueAt(jlNomeProduto.getText(), tblVenda.getSelectedRow(), 1);
            modelo.setValueAt(tfQunatidade.getText(), tblVenda.getSelectedRow(), 2);
            modelo.setValueAt(valorun, tblVenda.getSelectedRow(), 3);
            modelo.setValueAt(valortotal, tblVenda.getSelectedRow(), 4);
            CartaoConsumacaoControl cartaoControl = new CartaoConsumacaoControl();
            long produto_id = Long.parseLong(tfProduto.getText());
            int prod_quant = Integer.parseInt(tfQunatidade.getText());
            cartaoControl.produtoMovimentacaoAtulizar(produto_id, venda_id, prod_quant);
        }
        calctotal();
    }//GEN-LAST:event_btnAtulizarActionPerformed

    private void btnDelatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelatarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tblVenda.getModel();
        String quantidade = tfQunatidade.getText();
        try {
            quant = Integer.parseInt(quantidade);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        valortotal = valorun * quant;

        if (tblVenda.getSelectedRow() == -1) {
            if (tblVenda.getRowCount() == 0) {
                jlMensagem.setText("Tabela sem produtos");
            } else {
                jlMensagem.setText("Selecione um produto");
            }
        } else {
            int x = JOptionPane.showConfirmDialog(this, "Deseja Deletar o Produto");
            if (x == 0) {
                CartaoConsumacaoControl cartaoControl = new CartaoConsumacaoControl();
                String produtoID = modelo.getValueAt(tblVenda.getSelectedRow(), 0).toString();
                long prod_id = Long.parseLong(produtoID);
                modelo.removeRow(tblVenda.getSelectedRow());
                cartaoControl.produtoMovimentacaoDelatar(venda_id, prod_id);
            }

        }
        calctotal();
    }//GEN-LAST:event_btnDelatarActionPerformed

    private void tblVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVendaMousePressed
        // TODO add your handling code here:
        jlMensagem.setText(null);
        DefaultTableModel modelo = (DefaultTableModel) tblVenda.getModel();
        tfProduto.setText(modelo.getValueAt(tblVenda.getSelectedRow(), 0).toString());
        jlNomeProduto.setText(modelo.getValueAt(tblVenda.getSelectedRow(), 1).toString());
        tfQunatidade.setText(modelo.getValueAt(tblVenda.getSelectedRow(), 2).toString());

    }//GEN-LAST:event_tblVendaMousePressed

    private void btnFecharVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharVendaActionPerformed
        // TODO add your handling code here:

        if (saldo < total) {
            JOptionPane.showMessageDialog(this, "Operação Saldo Insuficiene");
            fechar++;
            if (fechar == 3) {
                /*chamdno o evento do botão cancelar venda*/
                btnDelatarActionPerformed(evt);
                this.dispose();
                principal.setEnabled(true);
                principal.toFront();
            }
        } else {

            long numero = 0;

            try {
                numero = Long.parseLong(tfNumeroCartao.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Numero de Cartão invalido");
            }
            CartaoConsumacaoControl cartaoControl = new CartaoConsumacaoControl();
            long id_usuario = cartaoControl.pegarIdUsuarioProCartao(numero);
            cartaoControl.finalizarVendaCartao(venda_id, total, id_usuario);
            this.dispose();
            principal.setEnabled(true);
        }
    }//GEN-LAST:event_btnFecharVendaActionPerformed

    private void btnCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVendaActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Deseja Sair do Sistema ?");
        if (x == 0) {
            /*esse variave indica que a venda foi canselada*/
            int total_cancelar = 0;
            CartaoConsumacaoControl cartaoControl = new CartaoConsumacaoControl();
            cartaoControl.cancelarVendaCartao(total_cancelar);
            this.dispose();
            principal.setEnabled(true);
            principal.toFront();
        } else {
            this.toFront();
        }
    }//GEN-LAST:event_btnCancelarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasCartaoConsumacao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasCartaoConsumacao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasCartaoConsumacao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasCartaoConsumacao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasCartaoConsumacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtulizar;
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnDelatar;
    private javax.swing.JButton btnFecharVenda;
    private javax.swing.JButton btnInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlMensagem;
    private javax.swing.JLabel jlNomeProduto;
    private javax.swing.JLabel jlNomePropretario;
    private javax.swing.JLabel jlSaldo;
    private javax.swing.JLabel jlSaldoFuturo;
    private javax.swing.JLabel jlTotalCompra;
    private javax.swing.JTable tblVenda;
    private javax.swing.JTextField tfNumeroCartao;
    private javax.swing.JTextField tfProduto;
    private javax.swing.JTextField tfQunatidade;
    // End of variables declaration//GEN-END:variables
    /**
     * esse metodo abaixo atuliza o total da compra
     */
    protected void calctotal() {
        total = 0;
        double saldoFuturoCartao;

        DefaultTableModel modelo = (DefaultTableModel) tblVenda.getModel();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            total += (double) tblVenda.getValueAt(i, 4);
        }
        saldoFuturoCartao = saldo - total;

        jlTotalCompra.setText(String.valueOf(nf.format(total)));
        jlSaldoFuturo.setText(String.valueOf(nf.format(saldoFuturoCartao)));

    }

    /**
     * Metodo para ajudastar tamanho das coluna do Jtable
     */
    private void ajustarColunas() {
        tblVenda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblVenda.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblVenda.getColumnModel().getColumn(1).setPreferredWidth(290);
        tblVenda.getColumnModel().getColumn(2).setPreferredWidth(90);
        tblVenda.getColumnModel().getColumn(3).setPreferredWidth(90);
        tblVenda.getColumnModel().getColumn(4).setPreferredWidth(100);
    }

    /**
     * o Metodo abaixo Desabilita e bilita acesso aos botoes e campus
     *
     * @param habilita
     */
    private void hablitarDesabilitacapus(boolean habilita) {

        tfNumeroCartao.setEditable(habilita);
        tfProduto.setEditable(!habilita);
        tfQunatidade.setEditable(!habilita);
        btnInserir.setEnabled(!habilita);
        btnAtulizar.setEnabled(!habilita);
        btnDelatar.setEnabled(!habilita);
        btnFecharVenda.setEnabled(!habilita);
    }

}
